### PR TITLE
Fix bugs in liblj92 implementation.

### PR DESCRIPTION
**Pull request by FaresMehanna**
**Fixes Introduced:**
- Add mod operation in encoding and decoding which is necessary for 15 and 16 bits files.
- Increase arrays size when encoding to 18 instead of 17 which is also necessary for 15 and 16 bits files.
- Add "Adjust Bits" operation which fix a bug resulting in better compression ratio, the current implementation override the SSSS-0 category with a code-word full of one bits which very much increase it's code-word size and add a lot of unnecessary 0-bytes.

**MLV Tests:**
**Input:** 2x MLV file with 10bit lossless compression with sizes 138 MB - 2.51 GB.
**Implementation without  "Adjust Bits" Outputs:** lossless dng files with total size of 204 MB - 3.1 GB.
**Implementation with  "Adjust Bits" Outputs:** lossless dng files file with total size of 62.2 MB - 1.47 GB.
**Difference ratio:** 0.305 - 0.474.

Test file used to test the implementation: [here](https://github.com/FaresMehanna/MLV-File-Format/blob/master/LJPEG-1992/Andrew_Baldwin_Implementation/test.c)
Note, the test file works with the old API of liblj92, the one without the "int* components".
`
int lj92_open(lj92* lj, uint8_t* data, int datalen, int* width,int* height, int* bitdepth);
`
Not this one
`
int lj92_open(lj92* lj, uint8_t* data, int datalen, int* width,int* height, int* bitdepth, int* components);
`

### CODE REVIEW

**Comment by bouncyball-git** [comment]
This patch indeed gives better compression for real life MLVs.

Small example:

```
Uncompressed MLV             : 170,758,752 bytes
Compressed with original code: 109,123,729 bytes
Compressed with patched code : 108,619,437 bytes
```

This should not break anything (modifies only encoder).

@FaresMehanna: Thank you for this PR. I guess you are familiar with lj92 encoding/decoding quite a bit. Do you have any Idea about decoder, could it be optimized for even better speed?

**Comment by masc4ii** [comment]
@bouncyball-git & @ilia3101 : would you like to pull? I would like to commit something different too, but don't want to irritate github again... 😄

**Comment by FaresMehanna** [comment]
@bouncyball-git Thank you for the feedback.
I'm more interested in the encoding part since I'm implementing it in the FPGA for axiom cameras. I read the decoding part and it is quite good, there is few parts that can be optimized if you don't use linearization but it won't make big difference.
If you are more interested in the time taken in decoding rather than the throughput, it is possible to preprocess MLV file and split each frame to number of parts, and those parts can be decoded in parallel. 
If -even little- optimizations in decoding part is needed I can remove some unnecessary code, add some caching and try to do more optimization in "nextdiff" function.

**Comment by masc4ii** [comment]
> This should not break anything (modifies only encoder).

So I'll pull now. 
@FaresMehanna : thank you for this PR!

**Comment by bouncyball-git** [comment]
@FaresMehanna

> If you are more interested in the time taken in decoding rather than the throughput, it is possible to preprocess MLV file and split each frame to number of parts, and those parts can be decoded in parallel.

You mean decode each component separately?

> If -even little- optimizations in decoding part is needed I can remove some unnecessary code, add some caching and try to do more optimization in "nextdiff" function.

Would be very nice, thanks :)

**Comment by ilia3101** [comment]
> I'm more interested in the encoding part since I'm implementing it in the FPGA for axiom cameras.

Very impressive!

And cool to have someone from Axiom project here. is Axiom going to use MLV format? So Axiom cameras will be compatible with MLV App? 😍😍😍

**Comment by FaresMehanna** [comment]
Very sorry for my late reply!

@bouncyball-git 

> You mean decode each component separately?

It depends on what you mean by "component", in LJ92, if the frame is encoded in one scan even with multiple components they will not be separated components, they will be interleaved and a sequential decoding method will be used.

To make it parallel, one way is to create multiple scans and decode each one separately, but I don't know if this method is supported in DNG or not. another way which is supported in DNG is to reset the encoding operation after some pixels, by that you can detect the marks in advance, and start several decoders to decode each part separately, if some background process can recompress the files with different LJ92 parameters, it may be faster to decode in the future.

> > If -even little- optimizations in decoding part is needed I can remove some unnecessary code, add some caching and try to do more optimization in "nextdiff" function.
> 
> Would be very nice, thanks :)

I have looked online and there is a good library in dng sdk to encode/decode LJ92 images, I have yet to test and benchmark it to check how good/bad it is in comparison to the implemented one.
I will keep you updated.

**Comment by FaresMehanna** [comment]
@ilia3101 

> And cool to have someone from Axiom project here. 

I think I am the newest member in Axiom project 😄. I was influenced by your work on canon cameras. If hacking cameras got us that far, what if we build one?

> is Axiom going to use MLV format? So Axiom cameras will be compatible with MLV App? 😍😍😍

I believe yes! last year Supragya did a research and concluded that MLV will be good. here is [the research](http://supragyaraj.com/dev/gsoc-2018/).
We will know for sure once any of (USB3.0/emmc/SATA) modules get ready.

**Comment by bouncyball-git** [comment]
@FaresMehanna: Understood. Thanks for reply.

**Comment by ilia3101** [comment]
> @ilia3101
> 
> > And cool to have someone from Axiom project here.
> 
> I think I am the newest member in Axiom project :smile:. I was influenced by your work on canon cameras. If hacking cameras got us that far, what if we build one?

Completely agree about building a camera. Also can anyone 'join' the Axiom project?
> 
> > is Axiom going to use MLV format? So Axiom cameras will be compatible with MLV App? :heart_eyes::heart_eyes::heart_eyes: 
> 
> I believe yes! last year Supragya did a research and concluded that MLV will be good. here is [the research](http://supragyaraj.com/dev/gsoc-2018/).
> We will know for sure once any of (USB3.0/emmc/SATA) modules get ready.

This is very good to hear! And thanks for the link.

**Pull request merged**
