### PR TITLE
Add mcraw input file format

### PR DESCRIPTION
**Pull request by tlenke**
This PR adds support for the mcraw file format. 

The mcraw file format is created by MotionCam Pro (https://www.motioncamapp.com/), an app that runs on Android devices and allows them to capture RAW video. If you wish to try out the software, there is a free demo version available.

Only the structs required by the MLV format are used when loading an MCRAW file.

Support for this new format can potentially make MLV App available to a much larger audience.

### CODE REVIEW

**Comment by masc4ii** [comment]
Hej! Nice work! Is MCRAW so close to MLV? Unfortunately I can't test it, as I don't have any device supporting MotionCam around.

**Comment by tlenke** [comment]
Hi, if you want to try, here is a sample file: 
https://storage.googleapis.com/motioncamapp.com/samples/007-VIDEO_24mm-240328_141729.0.mcraw

In terms of metadata the two formats differ a lot, but of cause the basic RAW/bayer data is the same. Surprisingly it worked very well to "fake" the mlv and fill just enough oft the mlv structs to get it working.

I'm not familiar with your suggested raw2mlv; would this enable seamless integration such as drag-and-drop and straight open?

**Comment by ilia3101** [comment]
So exciting! Sounds great!

**Comment by masc4ii** [comment]
@ilia3101 So exiting this all sounds... I hope it doesn't break the main functionalites of MLVApp. I can not test it at all. So who knows... this change is very very deep. Seems brave to merge.

**Comment by masc4ii** [comment]
Compiling is broken.

**Comment by masc4ii** [comment]
```
/opt/homebrew/Cellar/llvm/16.0.6/lib/clang/16/include/immintrin.h:14: Fehler: "This header is only meant to be used on x86 and x64 architecture"
In file included from ../../src/mlv/mcraw/RawData.cpp:23:
/opt/homebrew/Cellar/llvm/16.0.6/lib/clang/16/include/immintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
```
,
```
/opt/homebrew/Cellar/llvm/16.0.6/lib/clang/16/include/mmintrin.h:14: Fehler: "This header is only meant to be used on x86 and x64 architecture"
In file included from ../../src/mlv/mcraw/RawData.cpp:23:
In file included from /opt/homebrew/Cellar/llvm/16.0.6/lib/clang/16/include/immintrin.h:21:
/opt/homebrew/Cellar/llvm/16.0.6/lib/clang/16/include/mmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
```
and all the functions which use this, are not compatible with ARM architecture, so won't run on any Mac since 2020. I would suggest to revert the merge and solve this first.

**Comment by masc4ii** [comment]
I found a `#if 1` in mcraw/RawData.cpp. When I set this to `#if 0` I can compile again. Is that a solution, from mcraw perspective?

**Comment by tlenke** [comment]
Your #ifndef __arm64 solution is a good workaround to successfully build the code on arm platform. The mcraw decoding will continue to work, but it will be very slow because the SIMD optimizations of the x86 branch are not effective.
 
The original code uses simde (https://github.com/simd-everywhere/simde) to maintain platform independence. To avoid introducing too many new dependencies, I limited the code to x86 at this moment. This is undoubtedly an optimization opportunity for the future.

**Pull request merged**
