### PR TITLE
Do not refresh scopes, when EditArea is not on screen.

### PR DESCRIPTION
**Pull request by Dobfek**
About 20-25% playback fps increase(on my Ryzen 7 2700, Windows 10).
Ugly tabs hopefully fixed.

### CODE REVIEW

**Comment by masc4ii** [comment]
Yes... the code looks better now. 
But again bad news: I found a bug with this change: if you show the edit area, load "frame 1", then hide the edit area and load "frame 2", and finally show the edit area again. You now will see the scope for "frame 1", not for "frame 2". That is wrong.

**Comment by Dobfek** [comment]
I try to replicate this issue. On Windows on FrameX, I turn off the EditArea. Pick another frame randomly(FrameY), and turn the EditArea on, it shows the histogram for FrameX for a fraction of a second, and refreses to the histogram of FrameY. I don't know what event makes a redraw, but seemingly it is not the case on OSX? I can make a YT video about it, if it might help.

**Comment by Dobfek** [comment]
Okay, I could replicate your problem. In on_dockWidgetEdit_visibilityChanged function, I commented out the m_frameChanged = true; line, so it makes the same problem you encountered. So on Windows this function is the one what makes it work fine.

**Comment by masc4ii** [comment]
Strange... compiled again, now it works. Lets merge. 😊 Thanks again!

**Comment by masc4ii** [comment]
Btw: Difference on my M1 for 5.7K 5D3 footage is 13 vs. 14 frames in playback on 2560x1600 display.

**Comment by Dobfek** [comment]
Yayy! Thanks for the merge! :)
I had 4,3k 1*3 footage(1440x1836) with the 3x stretch played at 10 fps, now it is 12-13 fps. Display resolution is 1920*1080.

**Pull request merged**
