### PR TITLE
MLV App with bayered raw data processing

### PR DESCRIPTION
**Pull request by bouncyball-git**

### CODE REVIEW

**Comment by bouncyball-git** [comment]
Yes agree. btw there is some conflict with the pro file. Will take a closer look at it tomorrow.

**Comment by masc4ii** [comment]
The conflict is just the line `win32: RC_ICON = ... ` which I added today. Should be easily merged.

**Comment by DeafEyeJedi** [comment]
Yeah sounds good!!!

**Comment by masc4ii** [comment]
What has to be done next to merge?

**Comment by bouncyball-git** [comment]
Strange conflict with .pro remains. Please try to merge and solve this conflict at the same time. I don't think I have merging right on that repository.

**Comment by masc4ii** [comment]
Merged. Hope it works. If not I'll fix it after PR. Can't be so complicated...

**Comment by bouncyball-git** [comment]
@masc: Hey great! There is no conflict any more!

@Ilia3101: Can you merge the pull request it's all your repository after all :)

**Comment by ilia3101** [comment]
Hope I did the merged correctly :)

**Comment by ilia3101** [comment]
Thanks for this! Can't wait to put stripe correction to use (my 5D2 has INTENSE stripes sometimes)

**Comment by bouncyball-git** [comment]
Wohoo! Merge successful, pulled and compiled all is running smoothly.

@Ilia3101: You are welcome! I liked from the 1st time your proggie and your desire to work on it (i wanted to write something like this myself) but unfortunately this was only for mac 9as usual ;) ) then Mr. Masc arrived and everything got straight and bright for Linux/Windows users. What can I say more, exiting times ehead :)

One more thing there are some problems with my and MLV App code interaction, especially when bad pixel fix is apllied (thanx to masc for finding this). I'm afraid this caused by race condition because getMlvRawFrameFloat() called from the get_mlv_raw_frame_debayered() which called from cache_mlv_frames() which runs as a thread. I'm still trying to catch this bug.

**Comment by bouncyball-git** [comment]
fpi and bpi means "focus pixel interpolation" and "bad pixel interpolation" methods respectively (I call them MLVFS and RAW2DNG methids for simplicity) and they are very different interpolation implementations. Sometimes on some footage it's better use one or another with the different results. So short answer is: yes should be selectable.

**Comment by bouncyball-git** [comment]
Regarding deflicker target, from 0 to 9999. Shortly 4 digit widget needed.

**Comment by bouncyball-git** [comment]
and fpi and bpi again. The method should be selectable separately for both. e.g:

focus pixelint  methd = 0 (0 - MLVFS, 1 - RAW2DNG)
bad pixel int method = 1 

by default I use 1 = RAW2DNG both (very good for focus pixels)

**Comment by ilia3101** [comment]
Seems like an intense bug :/
Does it happen only if cache function/thread is active? So would it be gone when cache thread is off?
If so, don't worry too much, as the cache thread will be replaced by a better method/thread/threads/function soon.

**Comment by bouncyball-git** [comment]
@ilia3101: how can I correctly switch off this thread?

**Comment by bouncyball-git** [comment]
Never mind I guess now I understand how you present caching works and that it's off for QT version by default.

**Comment by bouncyball-git** [comment]
Hey @masc4ii I found the reason why bad pixel fix is not working correctly on 1st load (both fix method which tries heuristically find anomalies in the raw data is affected, e.g: stripes fix, bad pixel fix)

This caused by the fact, that getMlvProcessedFrame8() gets called 2 times.
1. when previewPicture() is called (frame index is frame number / 2, e.g. the middle frame of the clip)
2. when drawFrame() is called (frame index is the slider's position, e.g. frame 0 on a fresh MLV)

How algorithm works:
For speed's sake bad pixel searching code looks up only 1st given frame of the given clip and adds all found pixel coordinates to the map, then just uses that map for remaining frames.

In our situation:
First previewPicture() gets called before any drawPicture(). That is why bad pixel code searches pixels in the middle frame of the clip, not frame 0. It of course depends on the clip itself and result calculated on the middle frame can be correct and should work on all frames, it's a little bit vague to me why this not working with my test clip which has very pronounced big pink hot pixel. 

Anyway when in previewPicture() I changed getMlvProcessedFrame8( m_pMlvObject, 0, m_pRawImage ), everything started working as expected.

I'm investigating this issue further.

**Comment by bouncyball-git** [comment]
Pushed a fix for this: commit a67cc50

**Comment by masc4ii** [comment]
@bouncyball-git : Is the behaviour of "bad pixels" right? If I have some bad pixels which are difficult to find for the function, I can try agrsv mode, okay? But when trying that, there is no difference. If I reload the file then (switching to another file and switching back while agrsv was checked) then the bad pixels are away... but now, they are away also in mode "on". Is the scan also made on first frame load? So there is no difference in the modes after that...

**Comment by bouncyball-git** [comment]
Scan only made on 1st call of applyLLRawProcObject(). In our case it was when previewPicture() got called. Now I made it to fix the raw only when drawFrame() gets called.

Normal vs aggressive bad pixel algorithms always give difference. Refer to console output for details. With aggressive more pixels are added to the map, could be even false alarmed ones.

Now on gui. Let's say bad pixel removal default is 'on' (NORMAL, when llrawproc.bad_pixels = 1) then switching to 'aggr' (AGRESSIVE, when llrawproc.bad_pixels = 2) also needs to reset llrawproc.bpm_status to 0, onChange of combobox to make the code search pixels again. In this case search will be done on the frame to which points slider position. This even might be a better way to manually specify the best frame with most pronounced cold/hot pixels to search :)

**Comment by ilia3101** [comment]
Switching it off is just a matter of commenting out calling the cache function everywhere you see it :)
... about 3 places maybe

Anyway you got it fixed?

Not got much time to read all the commits and messages on github (so much activty which is good!)

Will do major stuff later in the year when more time free(quite eager to).

**Comment by ilia3101** [comment]
Ah I see, you fixed it by not allowing the cache thread  to use it(the llrawprocobject) while you are requesting a frame from Qt GUI, I think is fine for now.
When cache is fixed that should be removed tho(?)

**Comment by bouncyball-git** [comment]
@masc4ii 
I think this will be the code:

//Combobox Bad Pixel changed
void MainWindow::on_comboBoxBadPixelsSwitch_currentIndexChanged(int index)
{
    //TODO: do it different!!!
    m_pMlvObject->llrawproc->bad_pixels = index;
    **m_pMlvObject->llrawproc->bpm_status = 0;**
    m_pMlvObject->current_cached_frame_active = 0;
    m_frameChanged = true;
}

@ilia3101: yes I think it is almost fixed. Some polishing needed for integration it to GUI.

**Comment by bouncyball-git** [comment]
@masc4ii: hmm.. sorry i was wrong not only bpm_status needs resetting.

I'll fix it and gonna push to the repo soon.

**Comment by masc4ii** [comment]
@bouncyball-git : okay, in one direction that works. But from agrsv to on I have to go over off. Okay... maybe you get it! :-) Thanks!

**Comment by bouncyball-git** [comment]
@masc4ii 
I think it's working now :) added one small routine reset_bpm_status() and  called from on_comboBoxBadPixelsSwitch_currentIndexChanged.

can you set default values on MLV open like:
Focus dots ON int 1
Bad pixels ON int 1
Chroma smooth OFF
Pattern noise OFF
Vertical stripes ON
Deflicker target 0

**Comment by bouncyball-git** [comment]
BTW what's your line "//TODO: do it different!!!" means? :) Do you need to rewrite all these functions later?!

**Comment by masc4ii** [comment]
@bouncyball-git : Cool, that works! Thanks! Should we call this also when changing the method?

I did switch all corrections OFF by default, because of performance reasons. The App feels slower when enabling all this nice stuff.

Do it different means: I don't want to write on structure of other moduls here, because this variables are a kind of "private", and I never really know what I do here. Moduls like llrawproc should offer "extern functions" which I call from the GUI to change the parameters. This would be my wish... ;-)

**Comment by bouncyball-git** [comment]
No method is for interpolating pixels not searching them (now gui is compressed here on my screen and aggr not showing in the widget fully also "Method" is little bit long word to squeeze in between widgets don't you think so? That's why I used "Int" which meant "interpolation"

I also noticed speed drop today but rather earlier in the morning. We should check commit history to find the changes which slowed things down.

"Do different": Now I understand what do you mean. "extern functions"... ok I' ll help you on this if you show me the example how it should look like :)

**Comment by masc4ii** [comment]
I did this little trick on my working copy: if all is off, video->llrawproc->fix_raw = 0. When enabling on of the correction features, it is slower (what is okay, or not?!). Shall I commit? But if you could find why it got slower, that would also be nice.

You are on Windows? I did not check, how it looks on Windows. On Mac it looks good... But I can check that. 
Btw: does it work for you on Windows? In the last days it nearly always crashed when I loaded a mlv file.

Okay... I'll try to show. Don't know when, but I will :-)

**Comment by bouncyball-git** [comment]
Tomorrow I'll try to detect the speed issue.

Nope I'm on Linux permanently. It's a long time since i rebooted to Win. Will check this tomorrow too.

OK :)

**Pull request merged**
